services:
  spring-app-1:
    build: .
    ports:
      - "8443:8443"
    volumes:
      - ./certificado.jks:/etc/ssl/CA/certificado.jks
      - ./logs/tomcat/app1:/usr/local/tomcat/logs  
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/clinifono
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: root
      SERVER_PORT: 8443
    networks:
      - rede-app
    container_name: spring-app-1
  spring-app-2:
    build: .
    ports:
      - "8444:8443"
    volumes:
      - ./certificado.jks:/etc/ssl/CA/certificado.jks
      - ./logs/tomcat/app2:/usr/local/tomcat/logs  
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/clinifono
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: root
      SERVER_PORT: 8443
    networks:
      - rede-app
    container_name: spring-app-2
  filebeat-backend:
    image: docker.elastic.co/beats/filebeat:8.14.0
    volumes:
      - ./filebeat.yml:/usr/share/filebeat/filebeat.yml:ro
      - ./logs/tomcat/app1:/usr/local/tomcat/logs/app1:ro
      - ./logs/tomcat/app2:/usr/local/tomcat/logs/app2:ro
    depends_on:
      - spring-app-1
      - spring-app-2
    networks:
      - rede-app
    container_name: filebeat-backend
  mysql:
    image: mysql:8.0
    container_name: mysql_local
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: clinifono
      MYSQL_USER: user
      MYSQL_PASSWORD: root
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - rede-app
      
volumes:
  mysql_data:

networks:
  rede-app:
    driver: bridge
